### ISSUE TITLE
linker command failed with exit code 1

### ISSUE THREAD

**Issue by sn4k3lab** [GertjanReynaert/react-native-universal#7]
Hey there, thank you for sharing this example app with us.
Im having some problems with Xcode when trying to build the app. Im getting the following error:

<img width="666" alt="screen shot 2017-03-27 at 12 05 53 am" src="https://cloud.githubusercontent.com/assets/6001184/24339299/311cb13e-1281-11e7-9f4f-57f33f30a065.png">

My settings:

> Xcode Version 8.2.1 (8C1002)
> react-native-cli: 2.0.1
> react-native: 0.7.1
> npm 4.1.2

Also im getting:

> Could not find dependencies.
> Ensure dependencies are installed - run 'npm install' from project root.

I have already install all dependencies with `npm install` and the error persists.
Thanks!

**Comment by GertjanReynaert** [comment]
I'm affraid that I can't really help you. Somehow I should redo this project, so the example is updated again. As you can see the example still uses React Native 0.7.1 where the current stable is 0.42.3.

For now I would recommend to just check the javascript source code for some guidance, but I wouldn't expect anything more from this example
